services:
#  yapper:
#    network_mode: bridge
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: unless-stopped
  yapper:
    network_mode: bridge
    image: bradganley/yapper:latest
    environment:
      - BSKY_IDENTIFIER=
      - BSKY_PASSWORD=
      - OPENAI_API_KEY=
      - GPTMODEL=
    restart: unless-stopped

